// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0yB1vwZMid1rixywPRWjWrhL6Ww--br0',
    appId: '1:475471855344:web:a343ecc8db264e38620c35',
    messagingSenderId: '475471855344',
    projectId: 'jagspoor',
    authDomain: 'jagspoor.firebaseapp.com',
    storageBucket: 'jagspoor.firebasestorage.app',
    measurementId: 'G-081EZX8F43',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDBoiJr9Tqwa0LIF24mGTmQFa-MJawyXM',
    appId: '1:475471855344:android:b74bed5488b2440b620c35',
    messagingSenderId: '475471855344',
    projectId: 'jagspoor',
    storageBucket: 'jagspoor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJiuCuUJTtKPDSpxXQ34cocUWMreyuBEk',
    appId: '1:475471855344:ios:304d79e1b9f96c36620c35',
    messagingSenderId: '475471855344',
    projectId: 'jagspoor',
    storageBucket: 'jagspoor.firebasestorage.app',
    androidClientId: '475471855344-pttv4g55mc1iuohnudtr0ee4d1vupbqd.apps.googleusercontent.com',
    iosClientId: '475471855344-g2htqcg7khu9tq92c500anih3m4bkdsq.apps.googleusercontent.com',
    iosBundleId: 'com.example.jagspoor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJiuCuUJTtKPDSpxXQ34cocUWMreyuBEk',
    appId: '1:475471855344:ios:304d79e1b9f96c36620c35',
    messagingSenderId: '475471855344',
    projectId: 'jagspoor',
    storageBucket: 'jagspoor.firebasestorage.app',
    androidClientId: '475471855344-pttv4g55mc1iuohnudtr0ee4d1vupbqd.apps.googleusercontent.com',
    iosClientId: '475471855344-g2htqcg7khu9tq92c500anih3m4bkdsq.apps.googleusercontent.com',
    iosBundleId: 'com.example.jagspoor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0yB1vwZMid1rixywPRWjWrhL6Ww--br0',
    appId: '1:475471855344:web:bef9bf4434a14523620c35',
    messagingSenderId: '475471855344',
    projectId: 'jagspoor',
    authDomain: 'jagspoor.firebaseapp.com',
    storageBucket: 'jagspoor.firebasestorage.app',
    measurementId: 'G-0CK5YN2PGF',
  );
}
