#!/usr/bin/env python3
"""Generate data/animals/spoor_classification_register.md.

CSV-driven over every species in assets/data/animals_seed.csv, with the
track-morphology values (toeCount / trackLengthMm / trackWidthMm) resolved
from the canonical TrackMorphology map in lib/utils/animal_seeder.dart (the
single source of truth for the Firestore `animals` spoor fields). Species
with no morphology entry are marked N/A (not track-relevant).

Run from the repo root:
    python3 data/animals/generate_register.py --write
"""
import csv
import re
from collections import Counter, OrderedDict
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[2]
SEED_CSV = ROOT / "assets" / "data" / "animals_seed.csv"
SEEDER = ROOT / "lib" / "utils" / "animal_seeder.dart"
OUT = ROOT / "data" / "animals" / "spoor_classification_register.md"

# Paper category grouping: animalType -> register section. Display order
# follows the dict insertion order.
PAPER_GROUPS = OrderedDict([
    ("Large Ungulates / Plains Game", [
        "Mammal (Antelope)", "Mammal (Equid)", "Mammal (Giraffid)", "Mammal (Pig)",
    ]),
    ("Small Antelope / Duikers", []),  # filled by explicit small-antelope set
    ("Dangerous Game & Protected Megafauna", [
        "Mammal (Dangerous Game)", "Mammal (Protected - Dangerous Game)",
        "Mammal (Protected)", "Mammal (Protected - Endangered)",
    ]),
    ("Predators (Felids, Canids, Hyaenids, Viverrids, Herpestids, Mustelids)", [
        "Mammal (Predator)", "Mammal (Predator - Dangerous)",
        "Mammal (Predator - medium)", "Mammal (Predator - small)",
    ]),
    ("Other Mammals (Hyrax, Lagomorph, Rodent, Primate, Other)", [
        "Mammal (Hyrax)", "Mammal (Lagomorph)", "Mammal (Rodent)",
        "Mammal (Primate)", "Mammal (Other)",
    ]),
    ("Reptiles", [
        "Reptile (Crocodilian)", "Reptile (Monitor)", "Reptile (Snake)",
        "Reptile (Protected)", "Reptile (Protected - Marine)",
        "Reptile (Protected - Endangered)", "Reptile (Protected - Vulnerable)",
    ]),
    ("Birds (Gamebird, Waterfowl, Pest, Protected)", [
        "Bird (Gamebird)", "Bird (Waterfowl)", "Bird (Pest)", "Bird (Protected)",
    ]),
])

# The 11 classic small antelope / duiker species (kept out of the large
# plains-game group so every species appears exactly once).
SMALL_ANTELOPE = {
    "common-duiker", "blue-duiker", "steenbok", "cape-grysbok",
    "sharpes-grysbok", "klipspringer", "oribi", "southern-reedbuck",
    "mountain-reedbuck", "suni", "natal-red-duiker",
}


def doc_id(name):
    return name.lower().replace(" ", "-").replace("'", "")


def parse_seeder_morphology(path):
    """Return {lower common name: TrackMorphology dict} parsed from
    animal_seeder.dart. This is the SINGLE source of truth for the Firestore
    `animals` spoor fields, so the register always agrees with the seeder."""
    src = Path(path).read_text(encoding="utf-8")
    m = re.search(
        r"_trackMorphology\s*=\s*<[^>]+>\s*\{(.*?)\n\s*\};", src, re.S
    )
    if not m:
        raise SystemExit(f"could not locate _trackMorphology map in {path}")
    body = m.group(1)
    entries = {}
    for am in re.finditer(
        r"(?:'([^']+)'|\"([^\"]+)\")\s*:\s*TrackMorphology\((.*?)\)\s*,", body, re.S
    ):
        key = (am.group(1) or am.group(2)).strip().lower()
        args = am.group(3)
        rec = {}
        for kv in re.findall(r"(\w+)\s*:\s*([^,]+)", args):
            rec[kv[0].strip()] = kv[1].strip()
        entries[key] = rec
    return entries


def main():
    write = "--write" in sys.argv
    seeder_map = parse_seeder_morphology(SEEDER)
    rows = list(csv.DictReader(SEED_CSV.open(encoding="utf-8")))

    # Assign each row to a section. The small-antelope / duiker set is
    # checked FIRST so those species get their own section instead of being
    # lumped into the large plains-game group.
    sections = OrderedDict((label, []) for label in PAPER_GROUPS)
    for r in rows:
        name = r["commonName"].strip()
        at = r["animalType"].strip()
        did = doc_id(name)
        section = None
        if at == "Mammal (Antelope)" and did in SMALL_ANTELOPE:
            section = "Small Antelope / Duikers"
        else:
            for label, types in PAPER_GROUPS.items():
                if label == "Small Antelope / Duikers":
                    continue
                if at in types:
                    section = label
                    break
        if section is None:
            section = "Other Mammals (Hyrax, Lagomorph, Rodent, Primate, Other)"
        sections[section].append(r)

    def morph_for(name):
        return seeder_map.get(name.lower())

    lines = []
    lines.append("# JagSpoor - SA Huntable & Plains Game Spoor Classification Register")
    lines.append("")
    lines.append("> Auto-generated by `data/animals/generate_register.py` from")
    lines.append("> `assets/data/animals_seed.csv` (species + category + huntable flag) and the")
    lines.append("> canonical `TrackMorphology` seeder map (`lib/utils/animal_seeder.dart`).")
    lines.append("> Do not edit by hand; extend the seeder map and regenerate.")
    lines.append("")
    lines.append(f"- Total species: **{len(rows)}**")
    lines.append(
        f"- Track-relevant species with morphology: **"
        f"{sum(1 for r in rows if morph_for(r['commonName'].strip()) is not None)}**"
    )
    lines.append("")
    lines.append(
        "Columns: `toeCount`, `trackLengthMinMm`, `trackLengthMaxMm`, "
        "`trackWidthMinMm`, `trackWidthMaxMm` (Firestore `animals` field names). "
        "A single histogram value is stored as min == max until a wider "
        "field-measured range is validated. `N/A` = not track-relevant."
    )
    lines.append("")
    lines.append("## Category summary")
    lines.append("")
    type_counts = Counter(r["animalType"].strip() for r in rows)
    for t, n in type_counts.most_common():
        lines.append(f"- **{t}**: {n}")
    lines.append("")
    lines.append(
        f"**Total: {len(rows)} species** "
        f"({sum(1 for r in rows if r['isHuntable'].strip() == 'TRUE')} huntable, "
        f"{sum(1 for r in rows if r['isHuntable'].strip() != 'TRUE')} protected/non-huntable)."
    )
    lines.append("")

    for label, group_rows in sections.items():
        if not group_rows:
            continue
        lines.append(f"## {label}")
        lines.append("")
        lines.append(
            "| ID | Common Name | Category | Huntable | ToeCount | "
            "Length min (mm) | Length max (mm) | Width min (mm) | Width max (mm) | Source |"
        )
        lines.append(
            "|----|-------------|----------|----------|----------|"
            "-----------------|-----------------|----------------|----------------|--------|"
        )
        for r in group_rows:
            name = r["commonName"].strip()
            at = r["animalType"].strip()
            huntable = r["isHuntable"].strip()
            morph = morph_for(name)
            if morph is None:
                toe = ln = wd = "N/A"
                status = "n/a"
            else:
                toe = morph.get("toeCount", "?")
                ln = morph.get("trackLengthMm", "?")
                wd = morph.get("trackWidthMm", "?")
                status = "established" if ln != "?" else "placeholder"
            lines.append(
                f"| `{doc_id(name)}` | {name} | {at} | {huntable} | {toe} "
                f"| {ln} | {ln} | {wd} | {wd} | {status} |"
            )
        lines.append("")

    out = "\n".join(lines) + "\n"
    if write:
        OUT.write_text(out, encoding="utf-8")
        print(f"wrote {OUT} ({len(rows)} species)")
    else:
        print(out)


if __name__ == "__main__":
    main()
